# Generated by Django 5.0.1 on 2024-02-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
