# Generated by Django 5.0.1 on 2024-02-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory_name', models.CharField(max_length=30)),
            ],
        ),
    ]
