# Generated by Django 5.0.1 on 2024-02-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelpic',
        ),
    ]
