# Generated by Django 5.0.1 on 2024-02-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelpic',
        ),
    ]
