# Generated by Django 5.0.1 on 2024-02-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelpic',
        ),
    ]
