# Generated by Django 5.0.1 on 2024-02-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelpic',
        ),
    ]
