# Generated by Django 5.0.1 on 2024-02-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_delete_tbl_modelpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_modelpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelpost_image', models.FileField(upload_to='Assets/Model/ModelPost_Image/')),
                ('modelpost_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.tbl_modelpost')),
            ],
        ),
    ]
