# Generated by Django 5.0.1 on 2024-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_caption', models.CharField(max_length=30)),
                ('post_amount', models.CharField(max_length=30)),
            ],
        ),
    ]
