# Generated by Django 5.0.1 on 2024-02-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_post',
        ),
    ]
