# Generated by Django 5.0.1 on 2024-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Photographers', '0002_delete_tbl_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_caption', models.CharField(max_length=30)),
                ('post_image', models.FileField(upload_to='Assets/Photographer/Post_Image/')),
                ('post_amount', models.CharField(max_length=30)),
            ],
        ),
    ]
