# Generated by Django 5.0.1 on 2024-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0004_tbl_addgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_photographerpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographerpost_title', models.CharField(max_length=30)),
                ('photographerpost_caption', models.CharField(max_length=30)),
                ('photographerpost_image', models.FileField(upload_to='Assets/Photographer/Post_Image/')),
                ('photographerpost_amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_post',
        ),
    ]
