# Generated by Django 5.0.1 on 2024-02-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0005_tbl_photographerpost_delete_tbl_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_photographerpost',
        ),
    ]
