# Generated by Django 5.0.1 on 2024-02-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0006_delete_tbl_photographerpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
    ]
