# Generated by Django 5.0.1 on 2024-02-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
    ]
