# Generated by Django 5.0.1 on 2024-02-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0029_tbl_addgallery'),
        ('Photographers', '0009_delete_tbl_addgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_editorbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.IntegerField(default=0)),
                ('ebooking_description', models.CharField(max_length=30)),
                ('ebooking_vstatus', models.IntegerField(default=0)),
                ('editor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_editorregistration')),
                ('photographer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographerregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_modelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.IntegerField(default=0)),
                ('mbooking_description', models.CharField(max_length=30)),
                ('mbooking_vstatus', models.IntegerField(default=0)),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_modelregistration')),
                ('photographer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographerregistration')),
            ],
        ),
    ]
