# Generated by Django 5.0.1 on 2024-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographers', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_editorbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_editorbooking',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_modelbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_modelbooking',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
