# Generated by Django 5.0.1 on 2024-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addgallery_image', models.FileField(upload_to='Assets/Editor/AddGallery_Image/')),
                ('addgallery_caption', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_editorpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorpost_title', models.CharField(max_length=30)),
                ('editorpost_caption', models.CharField(max_length=30)),
                ('editorpost_image', models.FileField(upload_to='Assets/Editor/Post_Image/')),
                ('editorpost_amount', models.CharField(max_length=30)),
            ],
        ),
    ]
