# Generated by Django 5.0.1 on 2024-02-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
        migrations.DeleteModel(
            name='tbl_editorpost',
        ),
    ]
