# Generated by Django 5.0.1 on 2024-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Editors', '0002_delete_tbl_addgallery_delete_tbl_editorpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addgallery_image', models.FileField(upload_to='Assets/Editor/AddGallery_Image/')),
                ('addgallery_caption', models.CharField(max_length=30)),
            ],
        ),
    ]
