# Generated by Django 5.0.1 on 2024-02-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editors', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
    ]
