# Generated by Django 5.0.1 on 2024-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_modelregistration',
            name='model_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbl_modelregistration',
            name='model_proof',
            field=models.ImageField(upload_to=''),
        ),
    ]
