# Generated by Django 5.0.1 on 2024-02-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_modelregistration_model_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelregistration',
        ),
    ]
