# Generated by Django 5.0.1 on 2024-02-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_place_tbl_subcategory'),
        ('Guest', '0003_delete_tbl_modelregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_modelregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('model_contact', models.CharField(max_length=30)),
                ('model_email', models.CharField(max_length=30)),
                ('model_address', models.CharField(max_length=30)),
                ('model_gender', models.CharField(max_length=30)),
                ('model_photo', models.FileField(upload_to='Assets/Model/Model_photo/')),
                ('model_proof', models.FileField(upload_to='Assets/Model/Model_proof/')),
                ('model_password', models.CharField(max_length=30)),
                ('model_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
