# Generated by Django 5.0.1 on 2024-02-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_modelregistration',
        ),
    ]
