# Generated by Django 5.0.1 on 2024-02-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place_tbl_subcategory'),
        ('Guest', '0009_delete_photographerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='photographerregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=30)),
                ('editor_contact', models.CharField(max_length=30)),
                ('editor_email', models.CharField(max_length=30)),
                ('editor_address', models.CharField(max_length=30)),
                ('editor_gender', models.CharField(max_length=30)),
                ('editor_username', models.CharField(max_length=30)),
                ('editor_photo', models.FileField(upload_to='Assets/Photographer/Photographer_photo/')),
                ('editor_proof', models.FileField(upload_to='Assets/Photographer/Photographer_proof/')),
                ('editor_active', models.CharField(max_length=30)),
                ('editor_password', models.CharField(max_length=30)),
                ('editor_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('editor_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
