# Generated by Django 5.0.1 on 2024-02-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_photographerregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photographerregistration',
        ),
    ]
