# Generated by Django 5.0.1 on 2024-02-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_ecategory'),
        ('Guest', '0016_tbl_editorregistration_editor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_editorregistration',
            name='editor_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ecategory'),
        ),
        migrations.AlterField(
            model_name='tbl_photographerregistration',
            name='photographer_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pcategory'),
        ),
    ]
