# Generated by Django 5.0.1 on 2024-02-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_tbl_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_post',
            old_name='post_name',
            new_name='post_title',
        ),
    ]
