# Generated by Django 5.0.1 on 2024-02-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0023_tbl_feedback'),
        ('Models', '0002_delete_tbl_modelpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='editor_id',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='photographer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_editorregistration',
            name='editor_category',
        ),
        migrations.RemoveField(
            model_name='tbl_editorregistration',
            name='editor_place',
        ),
        migrations.RemoveField(
            model_name='tbl_post',
            name='editor_id',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='editor_id',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='photographer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_modelregistration',
            name='model_place',
        ),
        migrations.RemoveField(
            model_name='tbl_photographerregistration',
            name='photographer_category',
        ),
        migrations.RemoveField(
            model_name='tbl_photographerregistration',
            name='photographer_place',
        ),
        migrations.RemoveField(
            model_name='tbl_post',
            name='photographer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_userregistration',
            name='user_place',
        ),
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_editorregistration',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_modelregistration',
        ),
        migrations.DeleteModel(
            name='tbl_photographerregistration',
        ),
        migrations.DeleteModel(
            name='tbl_post',
        ),
        migrations.DeleteModel(
            name='tbl_userregistration',
        ),
    ]
