# Generated by Django 5.0.1 on 2024-02-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0025_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addgallery',
        ),
    ]
