# Generated by Django 5.0.1 on 2024-02-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0026_delete_tbl_addgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addgallery_id', models.CharField(max_length=30)),
                ('addgallery_caption', models.CharField(max_length=30)),
                ('addgallery_image', models.FileField(upload_to='Assets/Guest/Add_Gallery/')),
                ('p_status', models.CharField(max_length=30)),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_post')),
            ],
        ),
    ]
