# Generated by Django 5.0.1 on 2024-03-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0030_tbl_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_epchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('editor_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_from', to='Guest.tbl_editorregistration')),
                ('editor_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_to', to='Guest.tbl_editorregistration')),
                ('photographer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographers_from', to='Guest.tbl_photographerregistration')),
                ('photographer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographers_to', to='Guest.tbl_photographerregistration')),
            ],
        ),
    ]
