# Generated by Django 5.0.1 on 2024-03-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0031_tbl_epchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mpchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('model_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_from', to='Guest.tbl_modelregistration')),
                ('model_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_to', to='Guest.tbl_modelregistration')),
                ('photographer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographerss_from', to='Guest.tbl_photographerregistration')),
                ('photographer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographerss_to', to='Guest.tbl_photographerregistration')),
            ],
        ),
    ]
