# Generated by Django 5.0.1 on 2024-02-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_delete_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
