# Generated by Django 5.0.1 on 2024-02-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0029_tbl_addgallery'),
        ('User', '0006_delete_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_photographerbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.IntegerField(default=0)),
                ('pbooking_description', models.CharField(max_length=30)),
                ('pbooking_vstatus', models.IntegerField(default=0)),
                ('photographer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_photographerregistration')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
