# Generated by Django 5.0.1 on 2024-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_photographerbooking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
