# Generated by Django 5.0.4 on 2024-04-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0032_tbl_mpchat'),
        ('User', '0009_alter_tbl_photographerbooking_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
